apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-events
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  # Ignore differences at the specified json pointers
  ignoreDifferences:
  - kind: Service
    jsonPointers:
    - /spec/clusterIP
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-events
    targetRevision: "0.13.0"
    helm:
      releaseName: argo-events
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-events