apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sBannedConfigMapKeys
metadata:
  name: no-sshkeys-in-configmap
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["ConfigMap"]
  parameters:
    keys:
      - private_key
