name: "Code Change Labeler"
on: 
  - pull_request
jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v3-preview
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
